let standings = [
  {
    filters: {},
    competition: {
      id: 2014,
      area: {
        id: 2224,
        name: "Spain",
      },
      name: "Primera Division",
      code: "PD",
      plan: "TIER_ONE",
      lastUpdated: "2021-04-17T00:00:28Z",
    },
    season: {
      id: 635,
      startDate: "2020-09-13",
      endDate: "2021-05-23",
      currentMatchday: 37,
      winner: null,
    },
    standings: [
      {
        stage: "REGULAR_SEASON",
        type: "TOTAL",
        group: null,
        table: [
          {
            position: 1,
            team: {
              id: 78,
              name: "Club Atlético de Madrid",
              crestUrl: "https://crests.football-data.org/78.svg",
            },
            playedGames: 36,
            form: "W,D,W,L,W",
            won: 24,
            draw: 8,
            lost: 4,
            points: 80,
            goalsFor: 63,
            goalsAgainst: 23,
            goalDifference: 40,
          },
          {
            position: 2,
            team: {
              id: 86,
              name: "Real Madrid CF",
              crestUrl: "https://crests.football-data.org/86.svg",
            },
            playedGames: 36,
            form: "W,D,W,D,W",
            won: 23,
            draw: 9,
            lost: 4,
            points: 78,
            goalsFor: 64,
            goalsAgainst: 27,
            goalDifference: 37,
          },
          {
            position: 3,
            team: {
              id: 81,
              name: "FC Barcelona",
              crestUrl: "https://crests.football-data.org/81.svg",
            },
            playedGames: 36,
            form: "D,D,W,L,W",
            won: 23,
            draw: 7,
            lost: 6,
            points: 76,
            goalsFor: 83,
            goalsAgainst: 36,
            goalDifference: 47,
          },
          {
            position: 4,
            team: {
              id: 559,
              name: "Sevilla FC",
              crestUrl: "https://crests.football-data.org/559.svg",
            },
            playedGames: 36,
            form: "W,D,L,W,W",
            won: 23,
            draw: 5,
            lost: 8,
            points: 74,
            goalsFor: 52,
            goalsAgainst: 29,
            goalDifference: 23,
          },
          {
            position: 5,
            team: {
              id: 92,
              name: "Real Sociedad de Fútbol",
              crestUrl: "https://crests.football-data.org/92.svg",
            },
            playedGames: 36,
            form: "L,W,L,W,W",
            won: 15,
            draw: 11,
            lost: 10,
            points: 56,
            goalsFor: 54,
            goalsAgainst: 37,
            goalDifference: 17,
          },
          {
            position: 6,
            team: {
              id: 94,
              name: "Villarreal CF",
              crestUrl: "https://crests.football-data.org/94.svg",
            },
            playedGames: 36,
            form: "W,L,W,L,L",
            won: 14,
            draw: 13,
            lost: 9,
            points: 55,
            goalsFor: 55,
            goalsAgainst: 42,
            goalDifference: 13,
          },
          {
            position: 7,
            team: {
              id: 90,
              name: "Real Betis Balompié",
              crestUrl: "https://crests.football-data.org/90.svg",
            },
            playedGames: 36,
            form: "D,W,D,D,D",
            won: 15,
            draw: 10,
            lost: 11,
            points: 55,
            goalsFor: 46,
            goalsAgainst: 48,
            goalDifference: -2,
          },
          {
            position: 8,
            team: {
              id: 558,
              name: "RC Celta de Vigo",
              crestUrl: "https://crests.football-data.org/558.svg",
            },
            playedGames: 36,
            form: "W,W,W,W,L",
            won: 13,
            draw: 11,
            lost: 12,
            points: 50,
            goalsFor: 51,
            goalsAgainst: 53,
            goalDifference: -2,
          },
          {
            position: 9,
            team: {
              id: 77,
              name: "Athletic Club",
              crestUrl: "https://crests.football-data.org/77.svg",
            },
            playedGames: 36,
            form: "L,D,W,D,W",
            won: 11,
            draw: 13,
            lost: 12,
            points: 46,
            goalsFor: 46,
            goalsAgainst: 39,
            goalDifference: 7,
          },
          {
            position: 10,
            team: {
              id: 83,
              name: "Granada CF",
              crestUrl: "https://crests.football-data.org/83.svg",
            },
            playedGames: 36,
            form: "L,L,L,W,L",
            won: 13,
            draw: 6,
            lost: 17,
            points: 45,
            goalsFor: 45,
            goalsAgainst: 61,
            goalDifference: -16,
          },
          {
            position: 11,
            team: {
              id: 79,
              name: "CA Osasuna",
              crestUrl: "https://crests.football-data.org/79.svg",
            },
            playedGames: 36,
            form: "W,D,L,L,W",
            won: 11,
            draw: 11,
            lost: 14,
            points: 44,
            goalsFor: 36,
            goalsAgainst: 45,
            goalDifference: -9,
          },
          {
            position: 12,
            team: {
              id: 264,
              name: "Cádiz CF",
              crestUrl: "https://crests.football-data.org/264.svg",
            },
            playedGames: 36,
            form: "L,W,W,D,L",
            won: 11,
            draw: 10,
            lost: 15,
            points: 43,
            goalsFor: 33,
            goalsAgainst: 53,
            goalDifference: -20,
          },
          {
            position: 13,
            team: {
              id: 88,
              name: "Levante UD",
              crestUrl: "https://crests.football-data.org/88.svg",
            },
            playedGames: 36,
            form: "D,D,L,L,L",
            won: 9,
            draw: 13,
            lost: 14,
            points: 40,
            goalsFor: 43,
            goalsAgainst: 53,
            goalDifference: -10,
          },
          {
            position: 14,
            team: {
              id: 95,
              name: "Valencia CF",
              crestUrl: "https://crests.football-data.org/95.svg",
            },
            playedGames: 36,
            form: "L,W,L,D,L",
            won: 9,
            draw: 12,
            lost: 15,
            points: 39,
            goalsFor: 46,
            goalsAgainst: 52,
            goalDifference: -6,
          },
          {
            position: 15,
            team: {
              id: 263,
              name: "Deportivo Alavés",
              crestUrl: "https://crests.football-data.org/263.svg",
            },
            playedGames: 36,
            form: "W,D,L,D,W",
            won: 8,
            draw: 11,
            lost: 17,
            points: 35,
            goalsFor: 32,
            goalsAgainst: 54,
            goalDifference: -22,
          },
          {
            position: 16,
            team: {
              id: 82,
              name: "Getafe CF",
              crestUrl: "https://crests.football-data.org/82.svg",
            },
            playedGames: 36,
            form: "L,L,L,W,L",
            won: 8,
            draw: 10,
            lost: 18,
            points: 34,
            goalsFor: 26,
            goalsAgainst: 42,
            goalDifference: -16,
          },
          {
            position: 17,
            team: {
              id: 299,
              name: "SD Huesca",
              crestUrl: "https://crests.football-data.org/299.svg",
            },
            playedGames: 36,
            form: "W,L,W,L,L",
            won: 7,
            draw: 12,
            lost: 17,
            points: 33,
            goalsFor: 34,
            goalsAgainst: 52,
            goalDifference: -18,
          },
          {
            position: 18,
            team: {
              id: 250,
              name: "Real Valladolid CF",
              crestUrl: "https://crests.football-data.org/250.svg",
            },
            playedGames: 36,
            form: "L,L,D,D,D",
            won: 5,
            draw: 16,
            lost: 15,
            points: 31,
            goalsFor: 32,
            goalsAgainst: 51,
            goalDifference: -19,
          },
          {
            position: 19,
            team: {
              id: 278,
              name: "SD Eibar",
              crestUrl: "https://crests.football-data.org/278.svg",
            },
            playedGames: 36,
            form: "D,W,W,L,L",
            won: 6,
            draw: 12,
            lost: 18,
            points: 30,
            goalsFor: 28,
            goalsAgainst: 47,
            goalDifference: -19,
          },
          {
            position: 20,
            team: {
              id: 285,
              name: "Elche CF",
              crestUrl: "https://crests.football-data.org/285.svg",
            },
            playedGames: 36,
            form: "L,L,L,W,D",
            won: 6,
            draw: 12,
            lost: 18,
            points: 30,
            goalsFor: 29,
            goalsAgainst: 54,
            goalDifference: -25,
          },
        ],
      },
      {
        stage: "REGULAR_SEASON",
        type: "HOME",
        group: null,
        table: [
          {
            position: 1,
            team: {
              id: 78,
              name: "Club Atlético de Madrid",
              crestUrl: "https://crests.football-data.org/78.svg",
            },
            playedGames: 18,
            form: "",
            won: 14,
            draw: 3,
            lost: 1,
            points: 45,
            goalsFor: 39,
            goalsAgainst: 10,
            goalDifference: 29,
          },
          {
            position: 2,
            team: {
              id: 559,
              name: "Sevilla FC",
              crestUrl: "https://crests.football-data.org/559.svg",
            },
            playedGames: 18,
            form: "",
            won: 13,
            draw: 1,
            lost: 4,
            points: 40,
            goalsFor: 26,
            goalsAgainst: 11,
            goalDifference: 15,
          },
          {
            position: 3,
            team: {
              id: 86,
              name: "Real Madrid CF",
              crestUrl: "https://crests.football-data.org/86.svg",
            },
            playedGames: 18,
            form: "",
            won: 12,
            draw: 3,
            lost: 3,
            points: 39,
            goalsFor: 31,
            goalsAgainst: 12,
            goalDifference: 19,
          },
          {
            position: 4,
            team: {
              id: 81,
              name: "FC Barcelona",
              crestUrl: "https://crests.football-data.org/81.svg",
            },
            playedGames: 18,
            form: "",
            won: 11,
            draw: 5,
            lost: 2,
            points: 38,
            goalsFor: 43,
            goalsAgainst: 18,
            goalDifference: 25,
          },
          {
            position: 5,
            team: {
              id: 90,
              name: "Real Betis Balompié",
              crestUrl: "https://crests.football-data.org/90.svg",
            },
            playedGames: 18,
            form: "",
            won: 9,
            draw: 5,
            lost: 4,
            points: 32,
            goalsFor: 26,
            goalsAgainst: 21,
            goalDifference: 5,
          },
          {
            position: 6,
            team: {
              id: 77,
              name: "Athletic Club",
              crestUrl: "https://crests.football-data.org/77.svg",
            },
            playedGames: 18,
            form: "",
            won: 8,
            draw: 6,
            lost: 4,
            points: 30,
            goalsFor: 29,
            goalsAgainst: 18,
            goalDifference: 11,
          },
          {
            position: 7,
            team: {
              id: 92,
              name: "Real Sociedad de Fútbol",
              crestUrl: "https://crests.football-data.org/92.svg",
            },
            playedGames: 18,
            form: "",
            won: 8,
            draw: 6,
            lost: 4,
            points: 30,
            goalsFor: 30,
            goalsAgainst: 20,
            goalDifference: 10,
          },
          {
            position: 8,
            team: {
              id: 558,
              name: "RC Celta de Vigo",
              crestUrl: "https://crests.football-data.org/558.svg",
            },
            playedGames: 18,
            form: "",
            won: 9,
            draw: 3,
            lost: 6,
            points: 30,
            goalsFor: 28,
            goalsAgainst: 27,
            goalDifference: 1,
          },
          {
            position: 9,
            team: {
              id: 83,
              name: "Granada CF",
              crestUrl: "https://crests.football-data.org/83.svg",
            },
            playedGames: 18,
            form: "",
            won: 9,
            draw: 3,
            lost: 6,
            points: 30,
            goalsFor: 25,
            goalsAgainst: 25,
            goalDifference: 0,
          },
          {
            position: 10,
            team: {
              id: 95,
              name: "Valencia CF",
              crestUrl: "https://crests.football-data.org/95.svg",
            },
            playedGames: 18,
            form: "",
            won: 7,
            draw: 7,
            lost: 4,
            points: 28,
            goalsFor: 30,
            goalsAgainst: 22,
            goalDifference: 8,
          },
          {
            position: 11,
            team: {
              id: 94,
              name: "Villarreal CF",
              crestUrl: "https://crests.football-data.org/94.svg",
            },
            playedGames: 18,
            form: "",
            won: 7,
            draw: 6,
            lost: 5,
            points: 27,
            goalsFor: 25,
            goalsAgainst: 23,
            goalDifference: 2,
          },
          {
            position: 12,
            team: {
              id: 79,
              name: "CA Osasuna",
              crestUrl: "https://crests.football-data.org/79.svg",
            },
            playedGames: 18,
            form: "",
            won: 7,
            draw: 5,
            lost: 6,
            points: 26,
            goalsFor: 21,
            goalsAgainst: 22,
            goalDifference: -1,
          },
          {
            position: 13,
            team: {
              id: 88,
              name: "Levante UD",
              crestUrl: "https://crests.football-data.org/88.svg",
            },
            playedGames: 18,
            form: "",
            won: 5,
            draw: 8,
            lost: 5,
            points: 23,
            goalsFor: 25,
            goalsAgainst: 28,
            goalDifference: -3,
          },
          {
            position: 14,
            team: {
              id: 82,
              name: "Getafe CF",
              crestUrl: "https://crests.football-data.org/82.svg",
            },
            playedGames: 18,
            form: "",
            won: 5,
            draw: 6,
            lost: 7,
            points: 21,
            goalsFor: 13,
            goalsAgainst: 12,
            goalDifference: 1,
          },
          {
            position: 15,
            team: {
              id: 299,
              name: "SD Huesca",
              crestUrl: "https://crests.football-data.org/299.svg",
            },
            playedGames: 18,
            form: "",
            won: 5,
            draw: 6,
            lost: 7,
            points: 21,
            goalsFor: 17,
            goalsAgainst: 21,
            goalDifference: -4,
          },
          {
            position: 16,
            team: {
              id: 263,
              name: "Deportivo Alavés",
              crestUrl: "https://crests.football-data.org/263.svg",
            },
            playedGames: 18,
            form: "",
            won: 5,
            draw: 6,
            lost: 7,
            points: 21,
            goalsFor: 17,
            goalsAgainst: 23,
            goalDifference: -6,
          },
          {
            position: 17,
            team: {
              id: 285,
              name: "Elche CF",
              crestUrl: "https://crests.football-data.org/285.svg",
            },
            playedGames: 18,
            form: "",
            won: 4,
            draw: 8,
            lost: 6,
            points: 20,
            goalsFor: 16,
            goalsAgainst: 23,
            goalDifference: -7,
          },
          {
            position: 18,
            team: {
              id: 264,
              name: "Cádiz CF",
              crestUrl: "https://crests.football-data.org/264.svg",
            },
            playedGames: 18,
            form: "",
            won: 5,
            draw: 5,
            lost: 8,
            points: 20,
            goalsFor: 16,
            goalsAgainst: 27,
            goalDifference: -11,
          },
          {
            position: 19,
            team: {
              id: 250,
              name: "Real Valladolid CF",
              crestUrl: "https://crests.football-data.org/250.svg",
            },
            playedGames: 18,
            form: "",
            won: 3,
            draw: 7,
            lost: 8,
            points: 16,
            goalsFor: 18,
            goalsAgainst: 28,
            goalDifference: -10,
          },
          {
            position: 20,
            team: {
              id: 278,
              name: "SD Eibar",
              crestUrl: "https://crests.football-data.org/278.svg",
            },
            playedGames: 18,
            form: "",
            won: 2,
            draw: 7,
            lost: 9,
            points: 13,
            goalsFor: 12,
            goalsAgainst: 20,
            goalDifference: -8,
          },
        ],
      },
      {
        stage: "REGULAR_SEASON",
        type: "AWAY",
        group: null,
        table: [
          {
            position: 1,
            team: {
              id: 86,
              name: "Real Madrid CF",
              crestUrl: "https://crests.football-data.org/86.svg",
            },
            playedGames: 18,
            form: "",
            won: 11,
            draw: 6,
            lost: 1,
            points: 39,
            goalsFor: 33,
            goalsAgainst: 15,
            goalDifference: 18,
          },
          {
            position: 2,
            team: {
              id: 81,
              name: "FC Barcelona",
              crestUrl: "https://crests.football-data.org/81.svg",
            },
            playedGames: 18,
            form: "",
            won: 12,
            draw: 2,
            lost: 4,
            points: 38,
            goalsFor: 40,
            goalsAgainst: 18,
            goalDifference: 22,
          },
          {
            position: 3,
            team: {
              id: 78,
              name: "Club Atlético de Madrid",
              crestUrl: "https://crests.football-data.org/78.svg",
            },
            playedGames: 18,
            form: "",
            won: 10,
            draw: 5,
            lost: 3,
            points: 35,
            goalsFor: 24,
            goalsAgainst: 13,
            goalDifference: 11,
          },
          {
            position: 4,
            team: {
              id: 559,
              name: "Sevilla FC",
              crestUrl: "https://crests.football-data.org/559.svg",
            },
            playedGames: 18,
            form: "",
            won: 10,
            draw: 4,
            lost: 4,
            points: 34,
            goalsFor: 26,
            goalsAgainst: 18,
            goalDifference: 8,
          },
          {
            position: 5,
            team: {
              id: 94,
              name: "Villarreal CF",
              crestUrl: "https://crests.football-data.org/94.svg",
            },
            playedGames: 18,
            form: "",
            won: 7,
            draw: 7,
            lost: 4,
            points: 28,
            goalsFor: 30,
            goalsAgainst: 19,
            goalDifference: 11,
          },
          {
            position: 6,
            team: {
              id: 92,
              name: "Real Sociedad de Fútbol",
              crestUrl: "https://crests.football-data.org/92.svg",
            },
            playedGames: 18,
            form: "",
            won: 7,
            draw: 5,
            lost: 6,
            points: 26,
            goalsFor: 24,
            goalsAgainst: 17,
            goalDifference: 7,
          },
          {
            position: 7,
            team: {
              id: 90,
              name: "Real Betis Balompié",
              crestUrl: "https://crests.football-data.org/90.svg",
            },
            playedGames: 18,
            form: "",
            won: 6,
            draw: 5,
            lost: 7,
            points: 23,
            goalsFor: 20,
            goalsAgainst: 27,
            goalDifference: -7,
          },
          {
            position: 8,
            team: {
              id: 264,
              name: "Cádiz CF",
              crestUrl: "https://crests.football-data.org/264.svg",
            },
            playedGames: 18,
            form: "",
            won: 6,
            draw: 5,
            lost: 7,
            points: 23,
            goalsFor: 17,
            goalsAgainst: 26,
            goalDifference: -9,
          },
          {
            position: 9,
            team: {
              id: 558,
              name: "RC Celta de Vigo",
              crestUrl: "https://crests.football-data.org/558.svg",
            },
            playedGames: 18,
            form: "",
            won: 4,
            draw: 8,
            lost: 6,
            points: 20,
            goalsFor: 23,
            goalsAgainst: 26,
            goalDifference: -3,
          },
          {
            position: 10,
            team: {
              id: 79,
              name: "CA Osasuna",
              crestUrl: "https://crests.football-data.org/79.svg",
            },
            playedGames: 18,
            form: "",
            won: 4,
            draw: 6,
            lost: 8,
            points: 18,
            goalsFor: 15,
            goalsAgainst: 23,
            goalDifference: -8,
          },
          {
            position: 11,
            team: {
              id: 88,
              name: "Levante UD",
              crestUrl: "https://crests.football-data.org/88.svg",
            },
            playedGames: 18,
            form: "",
            won: 4,
            draw: 5,
            lost: 9,
            points: 17,
            goalsFor: 18,
            goalsAgainst: 25,
            goalDifference: -7,
          },
          {
            position: 12,
            team: {
              id: 278,
              name: "SD Eibar",
              crestUrl: "https://crests.football-data.org/278.svg",
            },
            playedGames: 18,
            form: "",
            won: 4,
            draw: 5,
            lost: 9,
            points: 17,
            goalsFor: 16,
            goalsAgainst: 27,
            goalDifference: -11,
          },
          {
            position: 13,
            team: {
              id: 77,
              name: "Athletic Club",
              crestUrl: "https://crests.football-data.org/77.svg",
            },
            playedGames: 18,
            form: "",
            won: 3,
            draw: 7,
            lost: 8,
            points: 16,
            goalsFor: 17,
            goalsAgainst: 21,
            goalDifference: -4,
          },
          {
            position: 14,
            team: {
              id: 250,
              name: "Real Valladolid CF",
              crestUrl: "https://crests.football-data.org/250.svg",
            },
            playedGames: 18,
            form: "",
            won: 2,
            draw: 9,
            lost: 7,
            points: 15,
            goalsFor: 14,
            goalsAgainst: 23,
            goalDifference: -9,
          },
          {
            position: 15,
            team: {
              id: 83,
              name: "Granada CF",
              crestUrl: "https://crests.football-data.org/83.svg",
            },
            playedGames: 18,
            form: "",
            won: 4,
            draw: 3,
            lost: 11,
            points: 15,
            goalsFor: 20,
            goalsAgainst: 36,
            goalDifference: -16,
          },
          {
            position: 16,
            team: {
              id: 263,
              name: "Deportivo Alavés",
              crestUrl: "https://crests.football-data.org/263.svg",
            },
            playedGames: 18,
            form: "",
            won: 3,
            draw: 5,
            lost: 10,
            points: 14,
            goalsFor: 15,
            goalsAgainst: 31,
            goalDifference: -16,
          },
          {
            position: 17,
            team: {
              id: 82,
              name: "Getafe CF",
              crestUrl: "https://crests.football-data.org/82.svg",
            },
            playedGames: 18,
            form: "",
            won: 3,
            draw: 4,
            lost: 11,
            points: 13,
            goalsFor: 13,
            goalsAgainst: 30,
            goalDifference: -17,
          },
          {
            position: 18,
            team: {
              id: 299,
              name: "SD Huesca",
              crestUrl: "https://crests.football-data.org/299.svg",
            },
            playedGames: 18,
            form: "",
            won: 2,
            draw: 6,
            lost: 10,
            points: 12,
            goalsFor: 17,
            goalsAgainst: 31,
            goalDifference: -14,
          },
          {
            position: 19,
            team: {
              id: 95,
              name: "Valencia CF",
              crestUrl: "https://crests.football-data.org/95.svg",
            },
            playedGames: 18,
            form: "",
            won: 2,
            draw: 5,
            lost: 11,
            points: 11,
            goalsFor: 16,
            goalsAgainst: 30,
            goalDifference: -14,
          },
          {
            position: 20,
            team: {
              id: 285,
              name: "Elche CF",
              crestUrl: "https://crests.football-data.org/285.svg",
            },
            playedGames: 18,
            form: "",
            won: 2,
            draw: 4,
            lost: 12,
            points: 10,
            goalsFor: 13,
            goalsAgainst: 31,
            goalDifference: -18,
          },
        ],
      },
    ],
  },
];
